services:
  postgres:
    image: postgres:17
    container_name: smart-postgres
    environment:
      POSTGRES_DB: smart_db
      POSTGRES_USER: smart_user
      POSTGRES_PASSWORD: smart_password
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: smart-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data: