server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_db
spring.datasource.username=smart_user
spring.datasource.password=smart_password

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init.sql

generator.datasource.jdbc-url=jdbc:postgresql://localhost:5432/smart_db?currentSchema=generated
generator.datasource.username=smart_user
generator.datasource.password=smart_password

llm.base-url=http://localhost:11434
llm.model=qwen3:1.7b